from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch
from PIL import Image


# 关键参数：EAAI 双栏通栏宽度 183 mm；位图按 600 dpi 输出。
WORKSPACE = Path(r"C:\Users\xsp\Desktop\DRL代码")
FROZEN_FIGURES = WORKSPACE / "paper_runs" / "multimap_v3_2_14" / "figures" / "paper_redraw_multibackend_v3"
SOURCE = FROZEN_FIGURES / "source_data"
DELIVERY = WORKSPACE / "paper_delivery" / "EAAI_2026-08-09"
MAIN_DIR = DELIVERY / "figures" / "main"
SUPP_DIR = DELIVERY / "figures" / "supplementary"
QA_DIR = DELIVERY / "qa" / "figure_qa"
WIDTH_MM = 183
DPI = 600

MODEL_LABELS = {
    "full": "PPO+Pointer",
    "a2c_pointer": "A2C+Pointer",
    "traditional_ppo": "Flat-MLP PPO",
    "nearest_feasible": "Nearest feasible",
    "priority_greedy": "Priority greedy",
    "aco": "ACO",
    "ga": "GA",
    "sa": "SA",
    "milp": "MILP",
    "a_star": "A*",
    "exact_pareto_dp": "Exact Pareto DP",
    "no_priority_bias": "No priority bias",
    "no_domain_randomization": "No domain randomization",
    "no_resource_shaping": "No resource shaping",
    "no_return_reserve": "No return reserve",
}

COLORS = {
    "full": "#2F6BBD",
    "a2c_pointer": "#F28E2B",
    "traditional_ppo": "#2A9D8F",
    "nearest_feasible": "#7F7F7F",
    "priority_greedy": "#59A14F",
    "aco": "#8E6C8A",
    "ga": "#EDC948",
    "sa": "#B07AA1",
    "milp": "#4E4E4E",
    "a_star": "#76B7B2",
    "exact_pareto_dp": "#E15759",
    "no_priority_bias": "#6B8E23",
    "no_domain_randomization": "#9467BD",
    "no_resource_shaping": "#8C564B",
    "no_return_reserve": "#A23E48",
}

mpl.rcParams.update(
    {
        "font.family": "Arial",
        "font.size": 8,
        "axes.titlesize": 9,
        "axes.labelsize": 8,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "axes.linewidth": 0.7,
        "grid.linewidth": 0.45,
        "lines.linewidth": 1.4,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "svg.fonttype": "none",
        "savefig.facecolor": "white",
        "figure.facecolor": "white",
    }
)


CAPTIONS = {
    "Fig01_method": "Fig. 1. Return-aware PPO–Pointer framework and evidence workflow. Candidate inspection points are encoded with priority-aware self-attention. The pointer policy scores variable-length candidates, while a deterministic feasibility mask excludes actions that cannot satisfy visit, dynamic, resource, and depot-return conditions. PPO updates use the frozen training protocol; all reported evidence is generated by the locked evaluation and map-level statistical pipeline.",
    "Fig02_coverage_priority": "Fig. 2. Coverage and priority effects on unseen synthetic maps and independent geographic digital surface model (DSM) simulations. (a) Map-level safe priority-weighted coverage across principal learning and optimisation comparators. Points are independent maps; box summaries are descriptive. (b) Priority-stratum coverage for PPO+Pointer and the no-priority-bias ablation. The priority bias did not produce a significant aggregate ablation effect, so stratum differences are reported descriptively.",
    "Fig03_safety_resources": "Fig. 3. Safety/return effects and resource use. (a) PPO+Pointer minus comparator percentage-point effects for safety and depot return under known shifts and hidden mismatch; intervals are the frozen map-level uncertainty estimates. (b) Median energy, distance, and time utilisation for safe routes. The return-aware mask maintained route feasibility, whereas the no-return-reserve ablation produced the dominant degradation.",
    "Fig04_time_tradeoff": "Fig. 4. Online planning time and quality–time trade-off. (a) Empirical cumulative distribution functions of online planning time. (b) Safe priority-weighted coverage versus 95th-percentile planning time; marker size encodes safe-route share. Classical optimisation can attain higher coverage in parts of the test set but requires substantially more online computation.",
    "Fig05_training": "Fig. 5. Training trajectories, stability, and sample efficiency. (a) Median safe priority-weighted coverage over five seeds with interquartile bands. (b) Frozen D6 training-stability and D7 sample-efficiency scores. PPO+Pointer and A2C+Pointer reach similar final coverage, while PPO+Pointer provides the stronger combined training profile.",
    "Fig06_transfer": "Fig. 6. Unseen-map performance and zero-shot geographic DSM simulation transfer. (a) Map-level estimates and uncertainty intervals on unseen procedural maps and eight independent Copernicus DSM regions. (b) Representative Taihang DSM simulation showing depot, inspection points, and planned routes over elevation. This is simulation-only geographic transfer, not flight validation.",
    "Fig07_robustness": "Fig. 7. Two-layer robustness. Cell values show retention relative to each model's reference performance for known domain shifts and hidden model/perception mismatch. Safe-route share is overlaid where available. The design separates perturbations represented during training from deliberately hidden evaluation errors.",
    "Fig08_ablation": "Fig. 8. Four-component ablation. Points show the Hodges–Lehmann estimate for PPO+Pointer minus each ablation, with frozen 95% hierarchical-bootstrap intervals. Removing the return reserve caused the only large, significant performance loss; the other individual removals did not support independent component claims under the confirmatory family.",
    "FigS01_performance_profile": "Fig. S1. Performance profiles based on regret from the safe priority-weighted coverage leader for each task.",
    "FigS03_oracle_compute": "Fig. S3. Oracle regret and online computation. Horizontal intervals show the frozen regret range; x positions use median planning time on a logarithmic scale.",
    "FigS04_scenario_heatmap": "Fig. S4. Scenario-stratified safe priority-weighted coverage across node count, terrain, wind, and resource-constraint factors.",
    "FigS05_failure_modes": "Fig. S5. Safety and return outcomes across robustness families and perturbation conditions.",
    "FigS06_all_training": "Fig. S6. Training trajectories for all seven learning models under the frozen 3,000-episode protocol.",
    "FigS07_dimensions": "Fig. S7. Seven-dimensional operational evidence profile. The 100-point aggregate is a post-hoc descriptive summary and is not a confirmatory champion metric.",
    "FigS08_sensitivity": "Fig. S8. Sensitivity of PPO+Pointer ranking to the operational floor and combined D6+D7 training weight.",
    "FigS09_synthetic_route": "Fig. S9. Representative fixed unseen synthetic task with roads, inspection priorities, and comparator routes.",
}


def mm_to_inches(mm: float) -> float:
    return mm / 25.4


def label_model(model: str) -> str:
    return MODEL_LABELS.get(model, model.replace("_", " ").title())


def style_axis(ax: plt.Axes) -> None:
    ax.grid(True, color="#E5E7EB", zorder=0)
    ax.spines[["top", "right"]].set_visible(False)
    ax.tick_params(length=3, width=0.6)


def panel_label(ax: plt.Axes, label: str) -> None:
    ax.text(-0.10, 1.05, label, transform=ax.transAxes, fontsize=10, fontweight="bold", va="top")


def save_figure(fig: plt.Figure, name: str, target: Path) -> list[dict]:
    target.mkdir(parents=True, exist_ok=True)
    records = []
    for extension in ("png", "pdf", "svg", "tiff"):
        path = target / f"{name}.{extension}"
        kwargs = {"bbox_inches": "tight", "pad_inches": 0.03}
        if extension in {"png", "tiff"}:
            kwargs["dpi"] = DPI
        fig.savefig(path, **kwargs)
        record = {"figure": name, "format": extension, "path": str(path), "bytes": path.stat().st_size, "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
        if extension in {"png", "tiff"}:
            with Image.open(path) as im:
                dpi_info = im.info.get("dpi")
                if isinstance(dpi_info, tuple):
                    dpi_info = [float(x) for x in dpi_info]
                record.update({"width_px": im.width, "height_px": im.height, "dpi": dpi_info})
        records.append(record)
    plt.close(fig)
    return records


def method_figure() -> plt.Figure:
    fig, ax = plt.subplots(figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(82)))
    ax.set_xlim(0, 12)
    ax.set_ylim(0, 6)
    ax.axis("off")
    boxes = [
        (0.25, 3.7, 2.1, 1.15, "Mountain-road task", "fixed points, priorities,\nterrain, wind, budgets", "#EAF2F8"),
        (2.75, 3.7, 2.1, 1.15, "Priority encoder", "15-D node features\n4-head self-attention", "#E8F5E9"),
        (5.25, 3.7, 2.1, 1.15, "Pointer policy", "UAV query + glimpse\nvariable candidate set", "#FFF3E0"),
        (7.75, 3.7, 2.1, 1.15, "Return-aware mask", "visit ∩ dynamics\n∩ energy ∩ distance\n∩ time and return", "#FDECEC"),
        (10.25, 3.7, 1.5, 1.15, "Action", "visit or\nreturn", "#F3E5F5"),
        (2.2, 1.0, 2.2, 1.15, "PPO learning", "clipped objective and GAE\n5 seeds × 3,000 episodes", "#EAF2F8"),
        (5.0, 1.0, 2.2, 1.15, "Frozen evaluation", "216 unseen-map tasks\n144 DSM tasks + robustness", "#E8F5E9"),
        (7.8, 1.0, 2.2, 1.15, "Map-level inference", "nonparametric tests\nHL effects + bootstrap", "#FFF3E0"),
    ]
    for x, y, w, h, title, body, color in boxes:
        patch = FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.03,rounding_size=0.08", facecolor=color, edgecolor="#475569", linewidth=0.9)
        ax.add_patch(patch)
        ax.text(x + w / 2, y + h * 0.68, title, ha="center", va="center", fontweight="bold", fontsize=7.5 if y > 2 else 7.0)
        ax.text(x + w / 2, y + h * 0.32, body, ha="center", va="center", fontsize=6.5 if y > 2 else 6.1, color="#334155")
    for x1, x2 in [(2.35, 2.75), (4.85, 5.25), (7.35, 7.75), (9.85, 10.25)]:
        ax.add_patch(FancyArrowPatch((x1, 4.27), (x2, 4.27), arrowstyle="-|>", mutation_scale=10, color="#475569", linewidth=1.0))
    ax.add_patch(FancyArrowPatch((6.3, 3.65), (3.3, 2.2), arrowstyle="-|>", connectionstyle="arc3,rad=.12", mutation_scale=10, color="#2F6BBD", linewidth=1.0))
    ax.add_patch(FancyArrowPatch((4.4, 1.58), (5.0, 1.58), arrowstyle="-|>", mutation_scale=10, color="#475569", linewidth=1.0))
    ax.add_patch(FancyArrowPatch((7.2, 1.58), (7.8, 1.58), arrowstyle="-|>", mutation_scale=10, color="#475569", linewidth=1.0))
    ax.text(6.0, 5.55, "Return-aware PPO–Pointer planning and locked evidence pipeline", ha="center", fontsize=11, fontweight="bold", color="#17365D")
    ax.text(6.0, 0.35, "Hard feasibility is enforced before action selection; reward shaping is secondary and separately ablated.", ha="center", fontsize=7.5, color="#475569")
    return fig


def coverage_priority_figure() -> plt.Figure:
    m01 = pd.read_csv(SOURCE / "M01_source_data.csv")
    m03 = pd.read_csv(SOURCE / "M03_source_data.csv")
    order = [x for x in ["full", "a2c_pointer", "traditional_ppo", "aco", "sa", "milp"] if x in set(m01.model)]
    fig, axes = plt.subplots(1, 2, figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(82)), gridspec_kw={"width_ratios": [1.25, 1]})
    ax = axes[0]
    offsets = {"synthetic": -0.16, "real": 0.16}
    markers = {"synthetic": "o", "real": "^"}
    rng = np.random.default_rng(42)
    for i, model in enumerate(order):
        for domain in ["synthetic", "real"]:
            vals = m01[(m01.model == model) & (m01.domain == domain)].weighted_coverage.to_numpy()
            if not len(vals):
                continue
            x = i + offsets[domain] + rng.normal(0, 0.025, len(vals))
            ax.scatter(x, vals, s=12, marker=markers[domain], facecolors="white", edgecolors=COLORS.get(model, "#555555"), linewidths=0.7, alpha=0.9, zorder=3)
            ax.plot([i + offsets[domain] - 0.09, i + offsets[domain] + 0.09], [np.median(vals)] * 2, color=COLORS.get(model, "#555555"), lw=2.1, zorder=4)
    ax.set_xticks(range(len(order)), [label_model(x) for x in order], rotation=30, ha="right")
    ax.set_ylabel("Safe priority-weighted coverage")
    ax.set_ylim(0.15, 0.66)
    ax.legend(handles=[Line2D([0], [0], marker="o", color="none", markeredgecolor="#334155", markerfacecolor="white", label="Unseen synthetic maps"), Line2D([0], [0], marker="^", color="none", markeredgecolor="#334155", markerfacecolor="white", label="Geographic DSM simulations")], frameon=False, loc="lower right")
    style_axis(ax); panel_label(ax, "a")

    ax = axes[1]
    domain_map = {"未见合成": "Unseen synthetic", "真实DSM": "Geographic DSM"}
    stratum_map = {"高优先级": "High", "中优先级": "Medium", "低优先级": "Low"}
    m03["domain_en"] = m03.domain.map(domain_map).fillna(m03.domain)
    m03["stratum_en"] = m03.stratum.map(stratum_map).fillna(m03.stratum)
    groups = [(d, s) for d in ["Unseen synthetic", "Geographic DSM"] for s in ["High", "Medium", "Low"] if len(m03[(m03.domain_en == d) & (m03.stratum_en == s)])]
    x = np.arange(len(groups))
    full = [float(m03[(m03.domain_en == d) & (m03.stratum_en == s)].full.iloc[0]) for d, s in groups]
    abl = [float(m03[(m03.domain_en == d) & (m03.stratum_en == s)].ablation.iloc[0]) for d, s in groups]
    ax.plot(x, full, "o-", color=COLORS["full"], label="PPO+Pointer", markersize=4)
    ax.plot(x, abl, "s--", color=COLORS["no_priority_bias"], label="No priority bias", markersize=4)
    ax.set_xticks(x, [s for _, s in groups])
    domain_spans = {}
    for idx, (domain, _) in enumerate(groups):
        domain_spans.setdefault(domain, []).append(idx)
    for domain, indices in domain_spans.items():
        ax.text(float(np.mean(indices)), -0.13, domain, transform=ax.get_xaxis_transform(), ha="center", va="top", fontsize=7)
    if len(domain_spans) > 1:
        first_count = len(next(iter(domain_spans.values())))
        ax.axvline(first_count - 0.5, color="#CBD5E1", lw=0.8)
    ax.set_ylabel("Coverage within priority stratum")
    ax.legend(frameon=False)
    style_axis(ax); panel_label(ax, "b")
    fig.tight_layout(w_pad=2.0)
    return fig


def safety_resources_figure() -> plt.Figure:
    m02 = pd.read_csv(SOURCE / "M02_source_data.csv")
    m04 = pd.read_csv(SOURCE / "M04_source_data.csv")
    fig, axes = plt.subplots(1, 2, figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(88)), gridspec_kw={"width_ratios": [1.15, 1]})
    ax = axes[0]
    layer = {"known_domain_shift": "Known shift", "hidden_model_perception_mismatch": "Hidden mismatch"}
    metric = {"safe": "Safe-route rate", "return": "Depot-return rate", "safe_rate": "Safe-route rate", "return_rate": "Depot-return rate"}
    selected = m02[m02.comparator.isin(["a2c_pointer", "traditional_ppo", "no_return_reserve"])].copy()
    selected["label"] = selected.apply(lambda r: f"{layer.get(r.layer, r.layer)} · {metric.get(r.metric, r.metric)} · {label_model(r.comparator)}", axis=1)
    selected = selected.sort_values(["layer", "metric", "comparator"])
    y = np.arange(len(selected))
    colors = [COLORS.get(x, "#555") for x in selected.comparator]
    ax.hlines(y, selected.ci_low_pp, selected.ci_high_pp, color=colors, lw=1.4)
    ax.scatter(selected.estimate_pp, y, c=colors, s=25, zorder=3)
    ax.axvline(0, color="#111827", ls="--", lw=0.8)
    ax.set_yticks(y, selected.label)
    ax.invert_yaxis()
    ax.set_xlabel("PPO+Pointer minus comparator (percentage points)")
    style_axis(ax); panel_label(ax, "a")

    ax = axes[1]
    metric_map = {"能耗": "Energy", "航程": "Distance", "总任务时间": "Mission time", "energy": "Energy", "distance": "Distance", "time": "Mission time"}
    models = [x for x in ["full", "a2c_pointer", "traditional_ppo"] if x in set(m04.model)]
    metrics = list(dict.fromkeys(metric_map.get(x, x) for x in m04.metric))
    for i, model in enumerate(models):
        subset = m04[m04.model == model]
        vals = []
        for m in metrics:
            row = subset[subset.metric.map(lambda z: metric_map.get(z, z)) == m]
            vals.append(float(row.utilization.iloc[0]) if len(row) else np.nan)
        ax.plot(np.arange(len(metrics)), vals, marker=["o", "s", "^"][i], color=COLORS[model], label=label_model(model))
    ax.set_xticks(np.arange(len(metrics)), metrics, rotation=20, ha="right")
    ax.set_ylabel("Median budget utilisation")
    ax.set_ylim(0, 1.02)
    ax.legend(frameon=False)
    style_axis(ax); panel_label(ax, "b")
    fig.tight_layout(w_pad=2.0)
    return fig


def time_tradeoff_figure() -> plt.Figure:
    m05 = pd.read_csv(SOURCE / "M05_source_data.csv")
    s02 = pd.read_csv(SOURCE / "S02_source_data.csv")
    fig, axes = plt.subplots(1, 2, figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(78)))
    ax = axes[0]
    for model, group in m05.groupby("model", sort=False):
        ax.step(group.planning_time_s, group.ecdf, where="post", color=COLORS.get(model, "#777"), label=label_model(model))
    ax.set_xscale("log")
    ax.set_xlabel("Online planning time (s, log scale)")
    ax.set_ylabel("Empirical cumulative probability")
    ax.legend(frameon=False, ncol=2, loc="lower right")
    style_axis(ax); panel_label(ax, "a")

    ax = axes[1]
    for _, row in s02.iterrows():
        model = row.model
        ax.scatter(row.planning_time_p95_s, row.D1, s=22 + 55 * float(row.safe_rate), color=COLORS.get(model, "#777"), edgecolor="white", linewidth=0.5, zorder=3)
        ax.annotate(label_model(model), (row.planning_time_p95_s, row.D1), xytext=(3, 2), textcoords="offset points", fontsize=6.5)
    ax.set_xscale("log")
    ax.set_xlabel("95th-percentile planning time (s)")
    ax.set_ylabel("D1: safe priority-weighted coverage")
    style_axis(ax); panel_label(ax, "b")
    fig.tight_layout(w_pad=2.3)
    return fig


def training_figure() -> plt.Figure:
    m06 = pd.read_csv(SOURCE / "M06_source_data.csv")
    m07 = pd.read_csv(SOURCE / "M07_source_data.csv")
    fig, axes = plt.subplots(1, 2, figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(78)), gridspec_kw={"width_ratios": [1.35, 1]})
    ax = axes[0]
    for model in ["full", "a2c_pointer", "traditional_ppo"]:
        g = m06[(m06.model == model) & m06["median"].notna()].sort_values("episodes_seen")
        if not len(g):
            seeds = m06[(m06.model == model) & (m06.record_type == "seed")]
            if not len(seeds):
                continue
            g = seeds.groupby("episodes_seen", as_index=False).safe_weighted_coverage.agg(["median", lambda x: x.quantile(.25), lambda x: x.quantile(.75)]).reset_index()
            g.columns = ["episodes_seen", "median", "q25", "q75"]
        x = g.episodes_seen.to_numpy(float); y = g["median"].to_numpy(float)
        ax.plot(x, y, color=COLORS[model], label=label_model(model))
        if "q25" in g and "q75" in g:
            ax.fill_between(x, g.q25.to_numpy(float), g.q75.to_numpy(float), color=COLORS[model], alpha=0.14, linewidth=0)
    ax.set_xlabel("Training episode")
    ax.set_ylabel("Safe priority-weighted coverage")
    ax.set_xlim(0, 3000)
    ax.set_ylim(0, 1.02)
    ax.legend(frameon=False)
    style_axis(ax); panel_label(ax, "a")

    ax = axes[1]
    metric_map = {"D6训练稳定性": "D6 stability", "D7样本效率": "D7 sample efficiency", "D6_training_stability": "D6 stability", "D7_sample_efficiency": "D7 sample efficiency"}
    for model in ["full", "a2c_pointer", "traditional_ppo"]:
        g = m07[m07.model == model]
        vals = {metric_map.get(row.metric, row.metric): float(row.score) for _, row in g.iterrows()}
        if "D6 stability" in vals and "D7 sample efficiency" in vals:
            ax.scatter(vals["D6 stability"], vals["D7 sample efficiency"], color=COLORS[model], s=45, label=label_model(model), zorder=3)
            ax.annotate(label_model(model), (vals["D6 stability"], vals["D7 sample efficiency"]), xytext=(4, 3), textcoords="offset points", fontsize=6.5)
    ax.set_xlabel("D6 training stability")
    ax.set_ylabel("D7 sample efficiency")
    ax.set_xlim(-0.03, 1.03); ax.set_ylim(-0.03, 1.03)
    style_axis(ax); panel_label(ax, "b")
    fig.tight_layout(w_pad=2.2)
    return fig


def transfer_figure() -> plt.Figure:
    m08 = pd.read_csv(SOURCE / "M08_source_data.csv")
    terrain = pd.read_csv(SOURCE / "V02" / "terrain.csv")
    points = pd.read_csv(SOURCE / "V02" / "points.csv")
    roads = pd.read_csv(SOURCE / "V02" / "roads.csv")
    routes = pd.read_csv(SOURCE / "V02" / "routes.csv")
    fig, axes = plt.subplots(1, 2, figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(82)), gridspec_kw={"width_ratios": [1, 1.25]})
    ax = axes[0]
    domain_map = {"synthetic": "Unseen synthetic", "real": "Geographic DSM", "未见合成地图": "Unseen synthetic", "真实DSM": "Geographic DSM"}
    models = [x for x in ["full", "a2c_pointer", "traditional_ppo"] if x in set(m08.model)]
    domains = list(dict.fromkeys(domain_map.get(x, x) for x in m08.domain))
    ybase = np.arange(len(domains))
    offsets = np.linspace(-0.18, 0.18, max(1, len(models)))
    for j, model in enumerate(models):
        for i, domain in enumerate(domains):
            g = m08[(m08.model == model) & (m08.domain.map(lambda z: domain_map.get(z, z)) == domain)]
            if not len(g):
                continue
            row = g.iloc[0]
            ax.errorbar(row.estimate, i + offsets[j], xerr=[[row.estimate - row.ci_low], [row.ci_high - row.estimate]], fmt="o", color=COLORS[model], ms=4, capsize=2, label=label_model(model) if i == 0 else None)
    ax.set_yticks(ybase, domains)
    ax.set_xlabel("Safe priority-weighted coverage")
    ax.set_xlim(0.2, 0.66)
    ax.legend(frameon=False)
    style_axis(ax); panel_label(ax, "a")

    ax = axes[1]
    nx = int(terrain.x.max()) + 1; ny = int(terrain.y.max()) + 1
    z = np.full((ny, nx), np.nan)
    z[terrain.y.astype(int), terrain.x.astype(int)] = terrain.z
    im = ax.imshow(z, origin="lower", cmap="terrain", alpha=0.82, extent=[0, nx - 1, 0, ny - 1], aspect="auto")
    for _, g in roads.groupby("road_id"):
        ax.plot(g.x, g.y, color="#374151", lw=0.7, alpha=0.8)
    for model in ["full", "a2c_pointer", "traditional_ppo"]:
        g = routes[routes.model == model].sort_values("sequence")
        if len(g):
            ax.plot(g.x, g.y, color=COLORS[model], lw=1.4, label=label_model(model))
    ins = points[points.point_type == "inspection"]
    depot = points[points.point_type != "inspection"]
    ax.scatter(ins.x, ins.y, c=ins.priority, cmap="YlOrRd", vmin=1, vmax=3, s=18, edgecolor="white", linewidth=0.4, zorder=4, label="Inspection point")
    if len(depot):
        ax.scatter(depot.x, depot.y, marker="*", s=80, color="#111827", edgecolor="white", linewidth=0.5, zorder=5, label="Depot")
    ax.set_xlabel("Local easting (30 m cells)"); ax.set_ylabel("Local northing (30 m cells)")
    ax.legend(frameon=True, facecolor="white", framealpha=0.85, fontsize=6, ncol=2, loc="lower right")
    cbar = fig.colorbar(im, ax=ax, fraction=0.038, pad=0.02); cbar.set_label("Elevation (m)")
    panel_label(ax, "b")
    fig.tight_layout(w_pad=2.0)
    return fig


def robustness_figure() -> plt.Figure:
    m09 = pd.read_csv(SOURCE / "M09_source_data.csv")
    model_order = [x for x in ["full", "a2c_pointer", "traditional_ppo", "no_domain_randomization", "no_return_reserve"] if x in set(m09.model)]
    conditions = list(dict.fromkeys(m09.condition))
    matrix = np.full((len(model_order), len(conditions)), np.nan)
    safe = np.full_like(matrix, np.nan)
    for i, model in enumerate(model_order):
        for j, condition in enumerate(conditions):
            g = m09[(m09.model == model) & (m09.condition == condition)]
            if len(g):
                matrix[i, j] = g.retention.mean()
                safe[i, j] = g.safe_rate.mean()
    fig, ax = plt.subplots(figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(72)))
    im = ax.imshow(matrix, cmap="YlGnBu", vmin=0.6, vmax=1.02, aspect="auto")
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if np.isfinite(matrix[i, j]):
                ax.text(j, i, f"{matrix[i,j]:.2f}\nS={safe[i,j]:.2f}", ha="center", va="center", fontsize=6, color="white" if matrix[i,j] > .84 else "#111827")
    ax.set_yticks(range(len(model_order)), [label_model(x) for x in model_order])
    ax.set_xticks(range(len(conditions)), [x.replace("_", " ").title() for x in conditions], rotation=30, ha="right")
    ax.set_xlabel("Perturbation condition"); ax.set_ylabel("Model")
    cbar = fig.colorbar(im, ax=ax, fraction=.022, pad=.02); cbar.set_label("Performance retention")
    ax.text(1.0, -0.20, "Cell: retention; S: safe-route share", transform=ax.transAxes, ha="right", fontsize=7, color="#475569")
    fig.tight_layout()
    return fig


def ablation_figure() -> plt.Figure:
    m10 = pd.read_csv(SOURCE / "M10_source_data.csv")
    domain_map = {"未见合成": "Unseen synthetic", "真实DSM": "Geographic DSM"}
    m10["domain_en"] = m10.domain.map(domain_map).fillna(m10.domain)
    m10["label"] = m10.apply(lambda r: f"{r.domain_en} · {label_model(r.comparator)}", axis=1)
    m10 = m10.sort_values(["domain_en", "comparator"])
    fig, ax = plt.subplots(figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(76)))
    y = np.arange(len(m10))
    colors = [COLORS.get(x, "#666") for x in m10.comparator]
    ax.hlines(y, m10.bootstrap_ci_low, m10.bootstrap_ci_high, color=colors, lw=1.5)
    ax.scatter(m10.hodges_lehmann, y, color=colors, s=26, zorder=3)
    ax.axvline(0, color="#111827", ls="--", lw=.8)
    ax.set_yticks(y, m10.label)
    ax.invert_yaxis()
    ax.set_xlabel("PPO+Pointer minus ablation (Hodges–Lehmann effect)")
    style_axis(ax)
    fig.tight_layout()
    return fig


def simple_supplementary(name: str) -> plt.Figure:
    fig, ax = plt.subplots(figsize=(mm_to_inches(WIDTH_MM), mm_to_inches(78)))
    if name == "FigS01_performance_profile":
        data = pd.read_csv(SOURCE / "S01_source_data.csv")
        for model, g in data.groupby("model", sort=False):
            ax.step(g.regret, g.ecdf, where="post", label=label_model(model), color=COLORS.get(model, "#777"))
        ax.set_xlabel("Safe-coverage regret"); ax.set_ylabel("Task fraction"); ax.legend(frameon=False, ncol=3); style_axis(ax)
    elif name == "FigS03_oracle_compute":
        data = pd.read_csv(SOURCE / "S03_source_data.csv").sort_values("planning_time_s")
        y = np.arange(len(data))
        ax.hlines(y, data.regret_low, data.regret_high, color="#64748B")
        ax.scatter(data.planning_time_s, y, c=[COLORS.get(x, "#777") for x in data.model], s=26)
        ax.set_xscale("log"); ax.set_yticks(y, [label_model(x) for x in data.model]); ax.set_xlabel("Median planning time (s, log scale)"); ax.set_ylabel("Solver / policy"); style_axis(ax)
    elif name == "FigS04_scenario_heatmap":
        data = pd.read_csv(SOURCE / "S04_source_data.csv")
        models = list(dict.fromkeys(data.model)); scenarios = list(dict.fromkeys(data.scenario))
        mat = np.full((len(models), len(scenarios)), np.nan)
        for i,m in enumerate(models):
            for j,s in enumerate(scenarios):
                g=data[(data.model==m)&(data.scenario==s)]
                if len(g): mat[i,j]=g["mean"].iloc[0]
        im=ax.imshow(mat,cmap="YlGnBu",vmin=0,vmax=.8,aspect="auto")
        ax.set_yticks(range(len(models)),[label_model(x) for x in models]); ax.set_xticks(range(len(scenarios)),[x.replace("｜"," · ").replace("_"," ") for x in scenarios],rotation=45,ha="right")
        fig.colorbar(im,ax=ax,fraction=.022,pad=.02,label="Mean safe weighted coverage")
    elif name == "FigS05_failure_modes":
        data = pd.read_csv(SOURCE / "S05_source_data.csv")
        data = data[data.metric.isin(["safe_rate","return_rate"])]
        rows=list(dict.fromkeys(data.apply(lambda r:f"{label_model(r.model)} · {r.metric.replace('_',' ')}",axis=1))); cols=list(dict.fromkeys(data.condition))
        mat=np.full((len(rows),len(cols)),np.nan)
        for _,r in data.iterrows(): mat[rows.index(f"{label_model(r.model)} · {r.metric.replace('_',' ')}"),cols.index(r.condition)]=r.raw_value
        im=ax.imshow(mat,cmap="YlGnBu",vmin=0,vmax=1,aspect="auto")
        ax.set_yticks(range(len(rows)),rows); ax.set_xticks(range(len(cols)),[x.replace("_"," ").title() for x in cols],rotation=35,ha="right"); fig.colorbar(im,ax=ax,fraction=.022,pad=.02,label="Rate")
    elif name == "FigS06_all_training":
        data = pd.read_csv(SOURCE / "S06_source_data.csv")
        for model,g in data.groupby("model",sort=False):
            g=g.sort_values("episodes_seen"); ax.plot(g.episodes_seen,g.weighted_coverage,label=label_model(model),color=COLORS.get(model,"#777"),lw=1.1)
            if {"q25","q75"}.issubset(g.columns): ax.fill_between(g.episodes_seen,g.q25,g.q75,color=COLORS.get(model,"#777"),alpha=.08,linewidth=0)
        ax.set_xlabel("Training episode"); ax.set_ylabel("Safe priority-weighted coverage"); ax.legend(frameon=False,ncol=3); style_axis(ax)
    elif name == "FigS07_dimensions":
        data = pd.read_csv(SOURCE / "S07_source_data.csv")
        metrics=list(dict.fromkeys(data.metric)); x=np.arange(len(metrics))
        for model,g in data.groupby("model",sort=False):
            vals=[float(g[g.metric==m].value_100.iloc[0]) if len(g[g.metric==m]) else np.nan for m in metrics]
            ax.plot(x,vals,marker="o",label=label_model(model),color=COLORS.get(model,"#777"))
        display_metrics=["Composite" if m=="综合得分" else m for m in metrics]
        ax.set_xticks(x,display_metrics); ax.set_ylabel("Dimension score (0–100)"); ax.set_ylim(0,102); ax.legend(frameon=False); style_axis(ax)
    elif name == "FigS08_sensitivity":
        data = pd.read_csv(SOURCE / "S08_source_data.csv")
        pivot=data.pivot_table(index="operational_floor",columns="training_weight",values="first_share",aggfunc="mean").sort_index().sort_index(axis=1)
        im=ax.imshow(pivot.values,origin="lower",aspect="auto",extent=[pivot.columns.min(),pivot.columns.max(),pivot.index.min(),pivot.index.max()],cmap="YlGnBu",vmin=0,vmax=1)
        ax.set_xlabel("Combined D6+D7 weight"); ax.set_ylabel("Operational floor"); fig.colorbar(im,ax=ax,fraction=.022,pad=.02,label="PPO+Pointer first-place share")
    elif name == "FigS09_synthetic_route":
        data = pd.read_csv(SOURCE / "V01_source_data.csv")
        for _,g in data[data.record_type=="road"].groupby("group"):
            ax.plot(g.x,g.y,color="#9CA3AF",lw=.8)
        pts=data[data.record_type.str.contains("point",case=False,na=False)]
        if len(pts): ax.scatter(pts.x,pts.y,c=pts.priority,cmap="YlOrRd",vmin=1,vmax=3,s=20,edgecolor="white",linewidth=.4,zorder=4)
        for model,g in data[data.model.notna() & (data.model.astype(str)!="")].groupby("model"):
            ax.plot(g.x,g.y,color=COLORS.get(model,"#777"),label=label_model(model),lw=1.3)
        ax.set_xlabel("Local easting (30 m cells)"); ax.set_ylabel("Local northing (30 m cells)"); ax.legend(frameon=False,ncol=3); ax.set_aspect("equal",adjustable="datalim"); style_axis(ax)
    fig.tight_layout()
    return fig


def main() -> None:
    MAIN_DIR.mkdir(parents=True, exist_ok=True); SUPP_DIR.mkdir(parents=True, exist_ok=True); QA_DIR.mkdir(parents=True, exist_ok=True)
    records = []
    builders = {
        "Fig01_method": method_figure,
        "Fig02_coverage_priority": coverage_priority_figure,
        "Fig03_safety_resources": safety_resources_figure,
        "Fig04_time_tradeoff": time_tradeoff_figure,
        "Fig05_training": training_figure,
        "Fig06_transfer": transfer_figure,
        "Fig07_robustness": robustness_figure,
        "Fig08_ablation": ablation_figure,
    }
    for name, builder in builders.items():
        records.extend(save_figure(builder(), name, MAIN_DIR))
    supp_names = ["FigS01_performance_profile", "FigS03_oracle_compute", "FigS04_scenario_heatmap", "FigS05_failure_modes", "FigS06_all_training", "FigS07_dimensions", "FigS08_sensitivity", "FigS09_synthetic_route"]
    for name in supp_names:
        records.extend(save_figure(simple_supplementary(name), name, SUPP_DIR))

    caption_text = "# English figure captions\n\n" + "\n\n".join(f"**{name}.** {caption}" for name, caption in CAPTIONS.items()) + "\n"
    (DELIVERY / "figures" / "captions_EN.md").write_text(caption_text, encoding="utf-8")
    qa = {
        "created_from": str(SOURCE),
        "data_changed": False,
        "language_and_layout_only_redraw": True,
        "width_mm": WIDTH_MM,
        "raster_dpi": DPI,
        "main_figure_count": len(builders),
        "supplementary_figure_count": len(supp_names),
        "outputs": records,
    }
    (QA_DIR / "figure_manifest_and_qa.json").write_text(json.dumps(qa, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"main": len(builders), "supplementary": len(supp_names), "files": len(records)}, indent=2))


if __name__ == "__main__":
    main()
